### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rchorda** [speth/ember#1]
Ember doesn't complete compilation due to the absence of function "initTranport" in cantera.

That function was eliminated from "include/cantera/transport/TransportFactory.h" in commit 873029503f41d76aa33c2bb62fb915adb635f140 at github cantera/cantera repository:

https://github.com/Cantera/cantera/commit/873029503f41d76aa33c2bb62fb915adb635f140

Same configurations for Sundials-Cantera-Ember successfully ends its compilación for 5fd0af9 versión  (previous  one in cantera repo).

Yours,
Ramón

**Comment by speth** [comment]
This is fixed by a combination of Cantera revision [r3412](https://code.google.com/p/cantera/source/detail?r=3412) and Ember revision cfb9e373e6bbde96d55f88e821bcc1629b97084d. Thanks for pointing out the problem.
